import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Select } from 'antd'
import { Input } from 'antd'
import Footer from '../components/Footer'
import Weblogo from '../public/weblogo.png'
import Google from '../public/google.png'
import Cat from '../public/cat1.png'
import Facebook from '../public/facebook.png'
import Style from '../styles/Login.module.css'

const { Option } = Select

const Login = () => {

    const [language, setLanguage] = useState("thai")
    const [email, setEmail] = useState("Email Address")
    const [password, setPassword] = useState("Password")
    const [login, setLogin] = useState("Login")
    const [or, setOr] = useState("or")

    const handleChange = (value) => {
        setLanguage(value)
    }

    useEffect(() => {
        if (language === "english") {
            setEmail("Email Address")
            setPassword("Password")
            setLogin("Login")
            setOr("or")
        } else {
            setEmail("อีเมล")
            setPassword("รหัสผ่าน")
            setLogin("เข้าสู่ระบบ")
            setOr("หรือ")
        }
    }, [language])

    return (
        <div>
            <Head>
                <title>Karsong | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={Style.navbar}>
                <div>
                    <Image
                        src={Weblogo}
                        alt="weblogo"
                        placeholder="blur"
                        height={90}
                        width={300}
                    />
                </div>
                <div>
                    <Select defaultValue="thai" style={{ width: 120 }} onChange={handleChange}>
                        <Option value="thai">ภาษาไทย</Option>
                        <Option value="english">English</Option>
                    </Select>
                </div>
            </div>
            <div className={Style.middle}>
                <div className={Style.content}>
                    <h1>ค้าส่งดอทคอม</h1>
                    <h2>ตอบโจทย์ธุรกิจคุณ</h2>
                    <Image src={Cat} alt="cat" height={50} width={60} />
                </div>
                <div className={Style.login}>
                    <p>{email}:</p>
                    <Input placeholder={email} />
                    <p>{password}:</p>
                    <Input.Password placeholder={password} />
                    <br /><br />
                    <button className={Style.loginbutton}>{login}</button>
                    <br /><br />
                    <p className={Style.line}>{or}</p>
                    <div className={Style.loginchoice}>
                        <Image src={Facebook} alt="facebook" placeholder="blur" width={50} height={50} />
                        &emsp;
                        <Image src={Google} alt="google" placeholder="blur" width={50} height={50} />
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default Login;