import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { Select, Input, Spin } from 'antd'
import Footer from '../components/Footer'
import Weblogo from '../public/karsonglogo2.png'
import Google from '../public/google.png'
import Cat from '../public/cat1.png'
import Facebook from '../public/facebook.png'
import Style from '../styles/Login.module.css'

const { Option } = Select

const Login = () => {

    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const [isCorrectEmail, setIsCorrectEmail] = useState(true)
    const [loading, setLoading] = useState(false)

    const onChangeEmail = (e) => {
        setEmail(e.target.value)
    }

    const onChangePassword = (e) => {
        setPassword(e.target.value)
    }

    const onSubmit = async () => {
        setLoading(true)
        if (email.toLowerCase()
            .match(
                /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
            ) && email !== "" && password !== "") {
            const result = await axios.post('http://localhost:4000/login', { email, password })
            console.log(result)
        } else {
            setIsCorrectEmail(false)
            setTimeout(() => {
                setIsCorrectEmail(true)
            }, 4000)
        }
        setLoading(false)
    }

    return (
        <div>
            <Head>
                <title>Karsong | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={Style.navbar}>
                <div className={Style.logoimage}>
                    <Image
                        src={Weblogo}
                        alt="weblogo"
                        placeholder="blur"
                        layout='fill'
                        objectFit='contain'
                    />
                </div>
                {/* <div>
                    <Select defaultValue="thai" style={{ width: 120 }} onChange={handleChange}>
                        <Option value="thai">ภาษาไทย</Option>
                        <Option value="english">English</Option>
                    </Select>
                </div> */}
            </div>
            <div className={Style.middle}>
                <div className={Style.content}>
                    <h1>ค้าส่งดอทคอม</h1>
                    <h2>ตอบโจทย์ธุรกิจคุณ</h2>
                    <Image src={Cat} alt="cat" height={50} width={60} />
                </div>
                <div className={Style.login}>
                    <p>
                        อีเมล:
                        <Input
                            placeholder="อีเมล"
                            value={email}
                            onChange={onChangeEmail}
                        />
                    </p>
                    <p>
                        รหัสผ่าน:
                        <Input.Password
                            placeholder="รหัสผ่าน"
                            value={password}
                            onChange={onChangePassword}
                        />
                    </p>
                    {!isCorrectEmail && <p style={{ color: 'red' }}>email รูปแบบไม่ถูกต้อง</p>}
                    <button
                        className={Style.loginbutton}
                        style={{ background: loading ? "rgba(0,128,0,0.5)" : "green" }}
                        onClick={onSubmit}
                        disabled={loading ? true : false}
                    >
                        เข้าสู่ระบบ
                    </button>
                    <br /><br />
                    <p className={Style.line}>หรือ</p>
                    <div className={Style.loginchoice}>
                        <Image src={Facebook} alt="facebook" placeholder="blur" width={50} height={50} />
                        &emsp;
                        <Image src={Google} alt="google" placeholder="blur" width={50} height={50} />
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default Login;