import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import axios from 'axios'
import { useCookies } from "react-cookie"
import { Select, Input, Spin } from 'antd'
import Footer from '../components/Footer'
import Weblogo from '../public/karsonglogo2.png'
import Google from '../public/google.png'
import Cat from '../public/cat1.png'
import Facebook from '../public/facebook.png'
import Style from '../styles/Login.module.css'

import api from '../api/api'

const { Option } = Select

const Login = ({ data }) => {
    const [cookie, setCookie] = useCookies(["token"])
    const router = useRouter()

    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const [isCorrectEmail, setIsCorrectEmail] = useState(true) // check email pattern
    const [loading, setLoading] = useState(false)
    const [message, setMessage] = useState("") //check email and password

    useEffect(async () => {
        try {
            const result = await axios.get(api.isloggedin, { headers: { 'x-access-token': data.token } })
            if (result.data.auth) router.push("/")
        } catch (err) {
            console.log(err)
        }
    }, [data])

    const onChangeEmail = (e) => {
        setEmail(e.target.value)
    }

    const onChangePassword = (e) => {
        setPassword(e.target.value)
    }

    const onSubmit = async () => {
        setLoading(true)
        if (email.toLowerCase().match(/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/)
            && email !== "" && password !== "") {
            try {
                const result = await axios.post(api.login, { email, password })
                if (result.data.auth) {
                    setCookie("token", result.data.token, {
                        path: "/",
                        maxAge: 2 * 24 * 60 * 60, // Expires after 1hr
                        sameSite: true,
                    })
                    router.push("/")
                } else {
                    setMessage(result.data.message)
                    setTimeout(() => {
                        setMessage("")
                    }, 5000)
                }
            } catch (err) {
                console.log(err)
            }
        } else {
            setIsCorrectEmail(false)
            setTimeout(() => {
                setIsCorrectEmail(true)
            }, 5000)
        }
        setLoading(false)
    }

    return (
        <div>
            <Head>
                <title>Karsong | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={Style.navbar}>
                <div className={Style.logoimage}>
                    <Image
                        src={Weblogo}
                        alt="weblogo"
                        placeholder="blur"
                        layout='fill'
                        objectFit='contain'
                    />
                </div>
                {/* <div>
                    <Select defaultValue="thai" style={{ width: 120 }} onChange={handleChange}>
                        <Option value="thai">ภาษาไทย</Option>
                        <Option value="english">English</Option>
                    </Select>
                </div> */}
            </div>
            <div className={Style.middle}>
                <div className={Style.content}>
                    <Image src="https://firebasestorage.googleapis.com/v0/b/karsongarcade.appspot.com/o/images%2Fstore.png?alt=media&token=a0494c8d-3a85-4286-b222-f8c1343f6134" layout='fill' objectFit='contain' />
                </div>
                <div className={Style.login}>
                    <p>
                        อีเมล:
                        <Input
                            placeholder="อีเมล"
                            value={email}
                            onChange={onChangeEmail}
                        />
                    </p>
                    <p>
                        รหัสผ่าน:
                        <Input.Password
                            placeholder="รหัสผ่าน"
                            value={password}
                            onChange={onChangePassword}
                        />
                    </p>
                    {!isCorrectEmail && <p style={{ color: 'red' }}>email รูปแบบไม่ถูกต้อง</p>}
                    <p style={{ color: 'red' }}>{message}</p>
                    <button
                        className={Style.loginbutton}
                        style={{ background: loading ? "rgba(0,128,0,0.5)" : "green" }}
                        onClick={onSubmit}
                        disabled={loading ? true : false}
                    >
                        เข้าสู่ระบบ
                    </button>
                    <br /><br />
                    <p className={Style.line}>หรือ</p>
                    <div className={Style.loginchoice}>
                        <Image src={Facebook} alt="facebook" placeholder="blur" width={50} height={50} />
                        &emsp;
                        <Image src={Google} alt="google" placeholder="blur" width={50} height={50} />
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export const getServerSideProps = async ({ req, res }) => {
    const { cookies } = req

    return {
        props: { data: cookies }
    }
}

export default Login;